export const BUFF_EXPIRY_CLUSTER_MIN_SECONDS = 21;
export const BUFF_EXPIRY_CLUSTER_MAX_SECONDS = 59;
export const BUFF_EXPIRY_CLUSTER_WINDOW_MS = 35_000;
export const BUFF_EXPIRY_CLUSTER_MERGE_WINDOW_MS = 3_000;
export const BUFF_EXPIRY_CLUSTER_INLIER_WINDOW_MS = 4_000;
export const BUFF_EXPIRY_CLUSTER_CONFIRM_SPREAD_MS = 3_000;
export const BUFF_EXPIRY_CLUSTER_CONFIRM_MIN_OBSERVATIONS = 4;
export const BUFF_EXPIRY_CLUSTER_CONFIRM_MIN_SPAN_MS = 5_500;
export const BUFF_EXPIRY_CLUSTER_CONFIRM_MIN_DECREASE = 6;
export const BUFF_EXPIRY_CLUSTER_FAST_CONFIRM_MIN_OBSERVATIONS = 3;
export const BUFF_EXPIRY_CLUSTER_FAST_CONFIRM_MIN_SPAN_MS = 3_000;
export const BUFF_EXPIRY_CLUSTER_FAST_CONFIRM_MIN_DISTINCT_SLOTS = 3;
export const BUFF_EXPIRY_CLUSTER_FAST_CONFIRM_STRONG_MIN_DISTINCT_SLOTS = 2;
export const BUFF_EXPIRY_CLUSTER_STRONG_DIVERSE_MIN_OBSERVATIONS = 4;
export const BUFF_EXPIRY_CLUSTER_STRONG_DIVERSE_MIN_SPAN_MS = 5_500;
export const BUFF_EXPIRY_CLUSTER_STRONG_DIVERSE_MIN_DISTINCT_SLOTS = 3;
export const BUFF_EXPIRY_CLUSTER_STRONG_DIVERSE_MIN_DISTINCT_BUFFS = 3;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_MIN_DISTINCT_BUFFS = 3;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MIN_OBSERVATIONS = 8;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MIN_SPAN_MS = 10_000;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MIN_DECREASE = 10;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MIN_SECONDS = 31;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MEMBER_MIN_OBSERVATIONS = 3;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MEMBER_MIN_SPAN_MS = 6_000;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MEMBER_MIN_DECREASE = 5;
export const BUFF_EXPIRY_CLUSTER_WEAK_ONLY_TWO_BUFF_MEMBER_MIN_AVERAGE_SCORE =
  0.88;
export const BUFF_EXPIRY_CLUSTER_MEMBER_MATCH_WINDOW_MS = 3_000;
export const BUFF_EXPIRY_CLUSTER_WEAK_MEMBER_MIN_OBSERVATIONS = 2;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_MIN_OBSERVATIONS = 5;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_MIN_SPAN_MS = 7_000;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_MIN_DECREASE = 6;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_MAX_SPREAD_MS = 2_000;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_MIN_ACCEPTED_OBSERVATIONS =
  2;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_MIN_ACCEPTED_SCORE = 0.92;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_MIN_AVERAGE_SCORE = 0.91;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_CLUSTER_ACCEPTED_PAIR_MIN_SPAN_MS =
  2_500;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_ACCEPTED_PAIR_MIN_SPAN_MS = 8_000;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_ACCEPTED_PAIR_MIN_DECREASE = 3;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_ACCEPTED_PAIR_MAX_SPREAD_MS = 1_000;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_ACCEPTED_PAIR_MAX_LATEST_SECONDS =
  40;
export const BUFF_EXPIRY_SINGLE_SMALL_POTION_ACCEPTED_PAIR_MAX_TIMING_DRIFT_SECONDS =
  1.25;
export const BUFF_EXPIRY_SINGLE_COUPON_CLUSTER_MIN_OBSERVATIONS = 5;
export const BUFF_EXPIRY_SINGLE_COUPON_CLUSTER_MIN_SPAN_MS = 8_000;
export const BUFF_EXPIRY_SINGLE_COUPON_CLUSTER_MIN_DECREASE = 8;
export const BUFF_EXPIRY_SINGLE_COUPON_CLUSTER_MAX_SPREAD_MS = 2_000;
export const BUFF_EXPIRY_SINGLE_COUPON_CLUSTER_MAX_GAP_MS = 6_500;
export const BUFF_EXPIRY_SINGLE_COUPON_CLUSTER_MIN_AVERAGE_SCORE = 0.89;
